stages:
  - test

image: golang

test:
  only:
    - merge_requests
  stage: test
  tags:
    - docker
  script:
    - apt update
    - apt install jq -y
    - apt install yamllint -y
    - make test
